/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve the main API endpoint
     * @description Returns API version, endpoints, rate limit, and a disclaimer.
     */
    get: operations['get-api-info'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/clades': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve all dinosaur clades
     * @description Retrieves all dinosaur clades.
     */
    get: operations['get-all-clades'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/diets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve all dinosaur diets
     * @description Retrieves all dinosaur diets.
     */
    get: operations['get-all-diets'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/locomotions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve all dinosaur locomotions
     * @description Retrieves all dinosaur locomotions.
     */
    get: operations['get-all-locomotions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/names': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve all dinosaur names
     * @description Retrieves all dinosaur names.
     */
    get: operations['get-all-names'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dinosaurs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve all dinosaurs
     * @description Retrieves all dinosaurs with pagination.
     */
    get: operations['get-all-dinosaurs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dinosaurs/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve a dinosaur by ID */
    get: operations['get-dinosaur-by-id'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dinosaurs/name/{name}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve dinosaur by name
     * @description Retrieves a specific dinosaur by its name. Name matching is case-insensitive.
     */
    get: operations['get-dinosaur-by-name'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dinosaurs/diet/{diet}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve dinosaurs by diet
     * @description Retrieves dinosaurs filtered by diet type. Diet matching is case-insensitive.
     */
    get: operations['get-dinosaurs-by-diet'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dinosaurs/locomotion/{locomotion}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve dinosaurs by locomotion
     * @description Retrieves all dinosaurs matching a specific locomotion type. Locomotion matching is case-insensitive.
     */
    get: operations['get-dinosaurs-by-locomotion'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dinosaurs/random/{count}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve a random number of dinosaurs */
    get: operations['get-random-dinosaurs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Search dinosaurs by clade, diet, and locomotion
     * @description Retrieves dinosaurs matching the provided query parameters. Matching is case-insensitive. Multiple clades may be provided as a comma-separated list.
     */
    get: operations['search-dinosaurs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/images': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve all dinosaur images
     * @description Accepts page query for pagination.
     */
    get: operations['get-all-images'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/images/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve a dinosaur image by ID */
    get: operations['get-image-by-id'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/images/random/{count}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve a random number of dinosaur images */
    get: operations['get-random-images'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Dinosaur: {
      /** @example 1118 */
      id: number;
      /** @example Zephyrosaurus */
      name: string;
      /** @example Early Cretaceous, ~113 Ma */
      temporalRange?: string;
      /** @example herbivore */
      diet?: string;
      /** @example biped */
      locomotionType?: string;
      /** @example Zephyrosaurus (meaning "westward wind lizard") is a genus of orodromine ornithischian dinosaur. */
      description?: string;
      classificationInfo: components['schemas']['ClassificationInfo'];
      image: components['schemas']['DinosaurImage'];
      source: components['schemas']['DinosaurSource'];
    };
    ClassificationInfo: {
      /** @example Eukaryota */
      domain?: string;
      /** @example Animalia */
      kingdom?: string;
      /** @example Chordata */
      phylum?: string;
      /**
       * @example [
       *       "Dinosauria",
       *       "Ornithischia"
       *     ]
       */
      clade?: string[];
      /**
       * @example [
       *       {
       *         "classType": "Class",
       *         "value": "Reptilia"
       *       }
       *     ]
       */
      classInfo?: {
        classType?: string;
        value?: string;
      }[];
      /**
       * @example [
       *       {
       *         "orderType": "Order",
       *         "value": "Ornithischia"
       *       }
       *     ]
       */
      orderInfo?: {
        orderType?: string;
        value?: string;
      }[];
      /**
       * @example [
       *       {
       *         "familyType": "Family",
       *         "value": "Thescelosauridae"
       *       },
       *       {
       *         "familyType": "Subfamily",
       *         "value": "Orodrominae"
       *       }
       *     ]
       */
      familyInfo?: {
        familyType?: string;
        value?: string;
      }[];
      /**
       * @example [
       *       {
       *         "tribeType": "Tribe",
       *         "value": "Thescelosaurini"
       *       }
       *     ]
       */
      tribeInfo?: {
        tribeType?: string;
        value?: string;
      }[];
      /**
       * @example [
       *       {
       *         "genusType": "Genus",
       *         "value": "Zephyrosaurus"
       *       }
       *     ]
       */
      genusInfo?: {
        genusType?: string;
        value?: string;
      }[];
      /**
       * @example [
       *       {
       *         "speciesType": "Species",
       *         "value": "Zephyrosaurus schaffi"
       *       }
       *     ]
       */
      speciesInfo?: {
        speciesType?: string;
        value?: string;
      }[];
    };
    DinosaurImage: {
      /** @example Zephyrosaurus in Copenhagen */
      title?: string;
      /** @example Zephyrosaurus skeleton, Natural History Museum of Denmark, Copenhagen. */
      description?: string;
      /** @example FunkMonk */
      author?: string;
      /**
       * Format: uri
       * @example https://commons.wikimedia.org/wiki/User:FunkMonk
       */
      authorURL?: string;
      /**
       * Format: uri
       * @example https://commons.wikimedia.org/wiki/File:Zephyrosaurus_in_Copenhagen.jpg
       */
      imageURL?: string;
      /** @example Creative Commons Attribution-Share Alike 3.0 */
      license?: string;
      /**
       * Format: uri
       * @example https://creativecommons.org/licenses/by-sa/3.0
       */
      licenseURL?: string;
      /**
       * Format: date-time
       * @example 2021-10-01T07:58:48.000Z
       */
      dateCreated?: string;
      /**
       * Format: date-time
       * @example 2024-01-30T14:27:20.683Z
       */
      dateAccessed?: string;
    };
    DinosaurSource: {
      /** @example Zephyrosaurus */
      pageTitle?: string;
      /** @example Wikipedia contributors */
      author?: string;
      /**
       * Format: uri
       * @example https://en.wikipedia.org/wiki/Zephyrosaurus
       */
      wikipediaURL?: string;
      /** @example Creative Commons Attribution-Share Alike 4.0 */
      license?: string;
      /**
       * Format: uri
       * @example https://creativecommons.org/licenses/by-sa/4.0/deed.en
       */
      licenseURL?: string;
      /**
       * Format: uri
       * @example https://en.wikipedia.org/w/index.php?title=Zephyrosaurus&oldid=1187326953
       */
      permalink?: string;
      /**
       * Format: uri
       * @example https://en.wikipedia.org/w/index.php?title=Zephyrosaurus&action=history
       */
      revisionHistoryURL?: string;
      /**
       * Format: date-time
       * @example 2023-11-28T15:28:47Z
       */
      lastRevision?: string;
      /**
       * Format: date-time
       * @example 2024-01-30T14:27:20.682Z
       */
      dateAccessed?: string;
      /** @example Wikipedia, The Free Encyclopedia */
      source?: string;
      /** @example Wikimedia Foundation */
      publisher?: string;
      /** @example Wikipedia contributors. "Zephyrosaurus." Wikipedia, The Free Encyclopedia. Wikimedia Foundation, 28 Nov 2023. Web. 30 Jan 2024. */
      citation?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'get-api-info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example v1 */
            apiVersion?: string;
            /**
             * @example {
             *       "home": "/api/v1",
             *       "getAllClades": "/api/v1/clades",
             *       "getAllDiets": "/api/v1/diets",
             *       "getAllLocomotions": "/api/v1/locomotions",
             *       "getAllNames": "/api/v1/names",
             *       "getAllDinos": "/api/v1/dinosaurs",
             *       "getDinoById": "/api/v1/dinosaurs/:id",
             *       "getDinoByName": "/api/v1/dinosaurs/name/:name",
             *       "getDinosByDiet": "/api/v1/dinosaurs/diet/:diet",
             *       "getDinosByLocomotion": "/api/v1/dinosaurs/locomotion/:locomotion",
             *       "getRandomDinos": "/api/v1/dinosaurs/random/:count",
             *       "getDinosaurByQuery": "/api/v1/search",
             *       "getAllImages": "/api/v1/images",
             *       "getImageById": "/api/v1/images/:id",
             *       "getRandomImages": "/api/v1/images/random/:count"
             *     }
             */
            apiEndpoints?: {
              [key: string]: string;
            };
            /** @example 20 requests per hour */
            rateLimit?: string;
            /** @example The information within the API is taken directly from Wikipedia, as is and may have been modified since the last time it was retrieved. All images and text belong to their respective authors and attribution is provided accordingly. */
            disclaimer?: string;
          };
        };
      };
    };
  };
  'get-all-clades': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of dinosaur clades with counts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @description Number of unique clade types
             * @example 12
             */
            uniqueClades?: number;
            data?: {
              /**
               * @description Clade name
               * @example Dinosauria
               */
              clade?: string;
              /**
               * @description Number of dinosaurs in this clade
               * @example 850
               */
              count?: number;
            }[];
          };
        };
      };
      /** @description No clades found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, there was an error retrieving all dinosaur clades */
            error?: string;
          };
        };
      };
      /** @description Unexpected error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred while retrieving all dinosaur clades */
            error?: string;
          };
        };
      };
    };
  };
  'get-all-diets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of dinosaur diets with counts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @description Number of unique diet types
             * @example 4
             */
            uniqueDiets?: number;
            data?: {
              /**
               * @description Diet type
               * @example carnivore
               * @enum {string}
               */
              diet?: 'carnivore' | 'herbivore' | 'omnivore' | 'piscivore';
              /**
               * @description Number of dinosaurs with this diet
               * @example 320
               */
              count?: number;
            }[];
          };
        };
      };
      /** @description No diets found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, there was an error retrieving all dinosaur diets */
            error?: string;
          };
        };
      };
      /** @description Unexpected error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred while retrieving all dinosaur diets */
            error?: string;
          };
        };
      };
    };
  };
  'get-all-locomotions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description A list of dinosaur locomotions with counts */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @description Number of unique locomotion types
             * @example 5
             */
            uniqueLocomotions?: number;
            data?: {
              /**
               * @description Locomotion type
               * @example biped
               * @enum {string}
               */
              locomotionType?: 'biped' | 'facultative biped' | 'gliding' | 'quadruped' | 'swimming';
              /**
               * @description Number of dinosaurs with this locomotion
               * @example 450
               */
              count?: number;
            }[];
          };
        };
      };
      /** @description No locomotions found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, there was an error retrieving all dinosaur locomotions */
            error?: string;
          };
        };
      };
      /** @description Unexpected error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred while retrieving all dinosaur locomotions */
            error?: string;
          };
        };
      };
    };
  };
  'get-all-names': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example 1188 */
            count?: number;
            /**
             * @example [
             *       "Zephyrosaurus",
             *       "Tyrannosaurus",
             *       "Velociraptor"
             *     ]
             */
            data?: string[];
          };
        };
      };
      /** @description No dinosaur names found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, there was an error retrieving all dinosaur names */
            error?: string;
          };
        };
      };
      /** @description Unexpected error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred while retrieving all dinosaur names */
            error?: string;
          };
        };
      };
    };
  };
  'get-all-dinosaurs': {
    parameters: {
      query?: {
        /** @description Page number to retrieve (50 items per page) */
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @description URL to previous page, empty string if first page
             * @example /api/v1/dinosaurs?page=1
             */
            prevPage?: string;
            /**
             * @description Current page number
             * @example 2
             */
            currentPage?: number;
            /**
             * @description URL to next page, empty string if last page
             * @example /api/v1/dinosaurs?page=3
             */
            nextPage?: string;
            /**
             * @description Number of items on current page
             * @example 50
             */
            count?: number;
            data?: components['schemas']['Dinosaur'][];
          };
        };
      };
      /** @description No dinosaurs found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, there was an error retrieving all dinosaurs */
            error?: string;
          };
        };
      };
      /** @description Unexpected error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred while retrieving all dinosaurs */
            error?: string;
          };
        };
      };
    };
  };
  'get-dinosaur-by-id': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dinosaur found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Dinosaur'];
        };
      };
      /** @description Dinosaur not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, there doesn't seem to be a dinosaur matching that id. */
            error?: string;
          };
        };
      };
      /** @description Unexpected error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred while retrieving a dinosaur matching the specified id. */
            error?: string;
          };
        };
      };
    };
  };
  'get-dinosaur-by-name': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example Tyrannosaurus */
        name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dinosaur found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Dinosaur'];
        };
      };
      /** @description Dinosaur not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, there doesn't seem to be a dinosaur matching that name. */
            error?: string;
          };
        };
      };
      /** @description Unexpected error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred trying to find a dinosaur matching that name. */
            error?: string;
          };
        };
      };
    };
  };
  'get-dinosaurs-by-diet': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example herbivore */
        diet: 'carnivore' | 'herbivore' | 'omnivore' | 'piscivore';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dinosaurs found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            count?: number;
            data?: components['schemas']['Dinosaur'][];
          };
        };
      };
      /** @description No dinosaurs matching diet */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, there doesn't seem to be any dinosaurs matching that diet. */
            error?: string;
          };
        };
      };
      /** @description Unexpected error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred while retrieving all dinosaurs matching that diet. */
            error?: string;
          };
        };
      };
    };
  };
  'get-dinosaurs-by-locomotion': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example biped */
        locomotion: 'biped' | 'facultative biped' | 'gliding' | 'quadruped' | 'swimming';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dinosaurs found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            count?: number;
            data?: components['schemas']['Dinosaur'][];
          };
        };
      };
      /** @description No dinosaurs matching locomotion */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, there doesn't seem to be any dinosaurs matching that locomotion type. */
            error?: string;
          };
        };
      };
      /** @description Unexpected error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred while retrieving all dinosaurs matching that locomotion. */
            error?: string;
          };
        };
      };
    };
  };
  'get-random-dinosaurs': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Number of random dinosaurs to retrieve (1-10) */
        count: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Random dinosaurs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            count?: number;
            data?: components['schemas']['Dinosaur'][];
          };
        };
      };
      /** @description Unexpected error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred while trying to retrieve a random number of dinosaurs. */
            error?: string;
          };
        };
      };
    };
  };
  'search-dinosaurs': {
    parameters: {
      query?: {
        /**
         * @description One or more clades. Can be provided as a comma-separated list (e.g. Dinosauria,Ornithischia).
         * @example [
         *       "Dinosauria"
         *     ]
         */
        clade?: string[];
        /** @example herbivore */
        diet?: 'carnivore' | 'herbivore' | 'omnivore' | 'piscivore';
        /** @example quadruped */
        locomotion?: 'biped' | 'facultative biped' | 'gliding' | 'quadruped' | 'swimming';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dinosaurs matching the query */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            count?: number;
            data?: components['schemas']['Dinosaur'][];
          };
        };
      };
      /** @description No dinosaurs matched the query */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, there doesn't seem to be any dinosaurs matching that query. */
            error?: string;
          };
        };
      };
      /** @description Server error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred while performing that query. */
            error?: string;
          };
        };
      };
    };
  };
  'get-all-images': {
    parameters: {
      query?: {
        page?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /**
             * @description URL to previous page, empty string if first page
             * @example /api/v1/images?page=1
             */
            prevPage?: string;
            /**
             * @description Current page number
             * @example 2
             */
            currentPage?: number;
            /**
             * @description URL to next page, empty string if last page
             * @example /api/v1/images?page=3
             */
            nextPage?: string;
            /**
             * @description Number of items on current page
             * @example 50
             */
            count?: number;
            data?: components['schemas']['DinosaurImage'][];
          };
        };
      };
      /** @description No images found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, there was an error retrieving all dinosaur images */
            error?: string;
          };
        };
      };
      /** @description Unexpected error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred while retrieving all dinosaur images */
            error?: string;
          };
        };
      };
    };
  };
  'get-image-by-id': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Image found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DinosaurImage'];
        };
      };
      /** @description Image not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, there doesn't seem to be a dinosaur image matching that id. */
            error?: string;
          };
        };
      };
      /** @description Unexpected error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred while trying to receive an image matching that id. */
            error?: string;
          };
        };
      };
    };
  };
  'get-random-images': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Number of random images to retrieve (1-10) */
        count: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Random images */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            count?: number;
            data?: components['schemas']['DinosaurImage'][];
          };
        };
      };
      /** @description Unexpected error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @example Sorry, an unexpected error occurred while trying to retrieve a random number of dinosaur images. */
            error?: string;
          };
        };
      };
    };
  };
}
